#ifndef _ENUM_SCREEN
#define _ENUM_SCREEN

enum Screen {
  SCREEN_SPLASH,
  SCREEN_MAIN_MENU,
  SCREEN_PROFILE_MENU,
  SCREEN_EDIT_DICE,
  SCREEN_ROLL_DICE,
  SCREEN_ROLL_SUMMARY,
  SCREEN_ROLL_BREAKDOWN
};

#endif
